creation_rules:
  - gcp_kms: projects/black-journal-436122-b5/locations/us-central1/keyRings/ica2-us/cryptoKeys/gke
    # Specify any file patterns you want to auto-encrypt
    path_regex: '.*\.yaml$'
    encrypted_regex: '^(data)$'
