apiVersion: v1
kind: ConfigMap
metadata:
  name: db
  namespace: ica2-db
data:
  # property-like keys; each key maps to a simple value
  POSTGRES_USER: admin
  POSTGRES_DB: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: ica2-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:13
        name: ica2-db
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: ica2-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db